// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaOjeQXATl6FeZjmYEdDsa4jjhfeTO1sY',
    appId: '1:563630810765:web:8de8d86dbae5404d57e4c4',
    messagingSenderId: '563630810765',
    projectId: 'act15-inventory-2a7b5',
    authDomain: 'act15-inventory-2a7b5.firebaseapp.com',
    storageBucket: 'act15-inventory-2a7b5.firebasestorage.app',
    measurementId: 'G-93XTEFQ2XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsC-RquWr2nIUGnCmowtkJI6Ztg1_eK6g',
    appId: '1:563630810765:android:bec275e8a56f247857e4c4',
    messagingSenderId: '563630810765',
    projectId: 'act15-inventory-2a7b5',
    storageBucket: 'act15-inventory-2a7b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNo3Oz3-2DUTuFgerCiC8K8oADT4arW2A',
    appId: '1:563630810765:ios:b72e9384732fc46a57e4c4',
    messagingSenderId: '563630810765',
    projectId: 'act15-inventory-2a7b5',
    storageBucket: 'act15-inventory-2a7b5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNo3Oz3-2DUTuFgerCiC8K8oADT4arW2A',
    appId: '1:563630810765:ios:b72e9384732fc46a57e4c4',
    messagingSenderId: '563630810765',
    projectId: 'act15-inventory-2a7b5',
    storageBucket: 'act15-inventory-2a7b5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaOjeQXATl6FeZjmYEdDsa4jjhfeTO1sY',
    appId: '1:563630810765:web:a6abfc29b3918a4757e4c4',
    messagingSenderId: '563630810765',
    projectId: 'act15-inventory-2a7b5',
    authDomain: 'act15-inventory-2a7b5.firebaseapp.com',
    storageBucket: 'act15-inventory-2a7b5.firebasestorage.app',
    measurementId: 'G-LFEBTCNJFL',
  );
}
